### ISSUE TITLE
jWizard radio buttons in IE 6, 7

### ISSUE THREAD

**Issue by ivoloshin** [dominicbarnes/jWizard#11]
Dominic,

First off, thank you for a great product you created! jWizard, is really cool and we like it a lot and plan to use it in our projects.

We did run into a small issue, however, and I was hoping you could point me in the right direction. You see, in testing using IE 6 and 7, whenever we have radio buttons in the panels and the user hits next and then previous, the radio button state is not restored. This works great in all the latest browsers, of course, but not in older IE.

Any ideas would be greatly appreciated!

Thank you!
Ilya

**Comment by dominicbarnes** [comment]
Hi there, sorry it took so long to respond to this!

In any case, I was able to recreate the problem you are referring to. Upon further research, I actually found out that this is a bug in jQuery UI itself. (see: http://bugs.jqueryui.com/ticket/3611)

I'm going to take some time to look into this, but even if I submit a patch to jQuery UI, it's unlikely it'll be released in the very near future, since I believe they just released a new version in the past few weeks.

Also, I am running Linux as my primary OS, so it's very difficult for me to diagnose the exact source of the problem since it's IE-specific. Any technical information you may have available would help immensely.

Thanks for using jWizard, I'm glad it's proven useful for you. :)

**Comment by ivoloshin** [comment]
Dominic,

Thanks for the response. As a workaround I added the following:

 _restoreRadioButtons: function() {
            if ( $.browser.msie && $.browser.version < 8 )
            {
                $.each($(':radio'), function(index, domElem) { 
                    var newRadioButton = $(domElem).clone(true);
                    $(domElem).replaceWith(newRadioButton);
                });
            }
        },

I then called it inside _changeStep after self._effect(nextStep, "step", "show", "show");

This is based on IE6 adn 7 not being able to change attributes on dynamically created elements. I cannot find the exact link talking about it, but I believe that's the real issue...

Thanks!
Ilya

**Comment by dominicbarnes** [comment]
So, I decided to be thorough, and I went to investigate this and hopefully submit a patch to jquery/ui in the end.

However, I actually came to discover that this is actually a bug in IE6/7 with their implementation of appendChild. It clears checkboxes and radio buttons whenever they are passed through appendChild.

It looks like this has been seen in other bug reports within both jQuery and jQuery UI, and the consensus has been that this is too obscure of an edge-case to put into jQuery itself.

Sorry about that, looks like your workaround function will have to do. :P
