### ISSUE TITLE
Events not fired

### ISSUE THREAD

**Issue by laoneo** [dominicbarnes/jWizard#6]
According to your documentation http://dominicbarnes.us/project-jwizard-documentation.php events should be fired. But they don't work. Or do I miss something....?

**Comment by dominicbarnes** [comment]
Sorry about that, I've got far too many pages to keep up to date when it comes to documentation :S

Refer to the github wiki for up-to-date documentation

**Comment by laoneo** [comment]
So is there no way we can get a notification? This is why I primary started to use your wizard.....Just making them available with different names is not an option for you? Can you then give me the commit where you removed them that I can integrate it into my fork....

**Comment by dominicbarnes** [comment]
I'm not sure which events you are referring to. `cancel` and `finish` are still the same, the only change is to `activate` and `deactivate`, because of huge problems in IE.

Now, you are to bind to `next` and `previous`. It's still a work-in-progress as far as these events go, but I've documented how it works atm here: http://github.com/desdev/jWizard/wiki/Custom-Events

Check this commit here as well: http://github.com/desdev/jWizard/commit/6745f12499d6a2d66d3e6a42efc05ba02a39cebe This is where the biggest changes to the underlying events had to take place.

**Comment by laoneo** [comment]
Thanks for the response, but I couldn't really figure out where did you remove the events. Is it not possible to make them available under a new name eg. wizardStepActivate and wizardStepDeactivate?

**Comment by dominicbarnes** [comment]
In addition to having to rename the events, I rewrote the underlying event triggering model to use the one jQuery UI provides in order to be consistent as well as leverage some extra functionality.

As of now, binding events to individual steps (ie. activate/deactivate) is no longer supported. Instead, an event is bound to the wizard itself that passes in the indexes of the current as well as next step in order to figure out what action to take.

Before, I was triggering the events in the _changeStep method, in case you wanted to add it back in there. I would recommend using the new events model, rather than trying to add the old system back in there.

**Comment by laoneo** [comment]
Thanks for the answer. From my point of view it should be possible that each step should be able to add some functionality to the wizard process beside the next and previous function of the wizard.
Anyway...keep up the good work :-)
